### ISSUE TITLE
Auto-open Camera

### ISSUE THREAD

**Issue by jacobstorms** [CollinDietz/AR-Poker-Hand-Identifier#12]
Camera needs to automatically open on app launch, maybe after a loading screen w/ app name + logo

**Comment by CollinDietz** [comment]
The loading screen thing is #7 so it should be enough to just remove the default jet. I'd vote we leave the debug bar at the bottom for right now, or at least only comment it out for now

**Comment by jacobstorms** [comment]
I think the ideal loading screen is actually the camera open with a semi-translucent logo + app name, then either a button or a default waiting time (2 seconds) before it transitions into detecting mode

**Comment by CollinDietz** [comment]
Is the easy/ do able? I was thinking copy the snapchat load, but use the same green and use whatever we make the icon replace the ghost

**Comment by jacobstorms** [comment]
Yeah I think that's what I had in mind too. Would be cool, not sure how technically difficult/ even-if-possible that is

**Comment by CollinDietz** [comment]
Enough to remove plane and hide debug bar but leave code to add it commented out
